### ISSUE TITLE
pytest fails without a clear reason

### ISSUE THREAD

**Issue by abearab** [ArcInstitute/ScreenPro2#24]
I updated [environment](https://github.com/ArcInstitute/ScreenPro2/blob/master/environment.yml) file and then, this action is failing even with an stable environment created – https://github.com/ArcInstitute/ScreenPro2/actions/workflows/python-package.yml

![image](https://github.com/ArcInstitute/ScreenPro2/assets/53412130/793a91c6-ca07-4475-9e9a-32fdc16ae548)

![image](https://github.com/ArcInstitute/ScreenPro2/assets/53412130/5aa6832a-21f7-4bad-bd8a-b42ac0319260)
___
Also, my local pytest is passing so I'm not sure what is happening!
![image](https://github.com/ArcInstitute/ScreenPro2/assets/53412130/6e1301e2-cfde-4239-a04c-000c6930e00a)

@nick-youngblut do you have any thoughts about this?

**Comment by nick-youngblut** [comment]
@abearab it's likely an issue with the numba version. A thread on the topic: https://github.com/openai/whisper/discussions/1103

**Comment by abearab** [comment]
@nick-youngblut Awesome!

https://github.com/ArcInstitute/ScreenPro2/commit/5ca8a1caf0f6d0f035bd204730992b9b27a5b624 – I added `numba` to be installed with pip and the test is now passed! Thanks 🙏
