### ISSUE TITLE
Question: library and sample format in cas9.py

### ISSUE THREAD

**Issue by akshitasax** [ArcInstitute/ScreenPro2#45]
Hello!

I am interested in using ScreenPro2/ScreenPro to analyze reads from a dual-guide CRISPR screen. Specifically, I wanted to get counts from my reads files and map them to my dual-guide library. I understand that user guidelines for the 'Fastq to counts' pipeline have not been posted to the readme yet, so I wanted to try to run the functions in Cas9.py on a jupyter notebook. What is the format of the dual-guide library that is given as an input in the map_sample_counts_to_library(library, sample) function? And is 'sample' the df_count returned by fastq_to_count_dual_guide()? 

Thank you,
Akshita

**Comment by abearab** [comment]
Hello Akshita,

Thanks for your interest in using ScreenPro2, happy to respond to any questions! 

> I understand that user guidelines for the 'Fastq to counts' pipeline have not been posted to the readme yet, so I wanted to try to run the functions in Cas9.py on a jupyter notebook.

Sounds like a good plan! As part of #44, I'm actively working on more user friendly interface for ScreenPro2. 

> What is the format of the dual-guide library that is given as an input in the map_sample_counts_to_library(library, sample) function? 

That's a good question! You need to have the have the library table and modify that based on your sequencing strategy. Can you tell me if what CRISPR library and sequencing protocol you are using? Is it from [Replogle et al., _eLife_ (2022)](https://elifesciences.org/articles/81856) and in that case your library-prep protocol should be [this](https://weissman.wi.mit.edu/resources/2022_crispri_protocols/Protocol_2_sequencing_library_preparation.pdf), right? Once you clarify I can help you run the codes in jupyter.

> And is 'sample' the df_count returned by fastq_to_count_dual_guide()?

That's true. This function is going to be changes in the next release. For the meantime, this is what I have done: I modified `df_count` to created a "sequence" column which would be matched with the "sequence" column in the `library` table. It depends on the sequencing strategy.

___
This is how I did fastq2count task for a dataset based on the [Replogle et al., _eLife_ (2022)](https://elifesciences.org/articles/81856) protocol:

```python
    df_count = cas9.fastq_to_count_dual_guide(
        R1_fastq_file_path=f'{fastq_dir}/{sample_id}_R1.fastq.gz',
        R2_fastq_file_path=f'{fastq_dir}/{sample_id}_R2.fastq.gz',
        trim5p_pos1_start=1,
        trim5p_pos1_length=19,
        trim5p_pos2_start=1,
        trim5p_pos2_length=19,
        verbose=verbose
    )
```

**Comment by abearab** [comment]
@akshitasax, in the meantime, if you don't mind please ⭐ the repo ;)

**Comment by abearab** [comment]
#47 discussed here.

**Comment by abearab** [comment]
@akshitasax – I think you get your answers here, right? Fell free to open new issue / reopen this / or email me if you have other questions.
